# Generated by Django 2.1.1 on 2018-10-01 18:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título da seção')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo da seção')),
                ('resume', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto descritivo')),
                ('image', models.ImageField(upload_to='images/about/', verbose_name='Imagem ou Logo')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Página ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Seção 'Sobre'",
                'verbose_name_plural': "Seções 'Sobre'",
            },
        ),
    ]
