# Generated by Django 2.1.1 on 2018-10-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nome')),
                ('subtitle', models.CharField(blank=True, max_length=50, verbose_name='Sub-título')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('image', models.ImageField(upload_to='images/speakers/', verbose_name='Avatar ou Foto')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='SpeakerSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Página ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Seção de 'Autor'",
                'verbose_name_plural': "Seções de 'Autores'",
            },
        ),
        migrations.AddField(
            model_name='speaker',
            name='speaker_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speaker_set', to='core.SpeakerSection', verbose_name='Seção relacionada'),
        ),
    ]
