# Generated by Django 2.1.1 on 2018-10-02 00:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181001_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do evento')),
                ('time', models.CharField(max_length=255, verbose_name='Horário')),
                ('resume', ckeditor.fields.RichTextField(blank=True, verbose_name='Descrição da Atividade')),
                ('local', models.CharField(max_length=255, verbose_name='Horário')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='ID Panel Heading')),
                ('collapse', models.CharField(blank=True, max_length=50, verbose_name='Link interno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Nome da categoria')),
                ('agenda', models.CharField(blank=True, max_length=50, verbose_name='Datas do evento')),
                ('anchor', models.CharField(blank=True, max_length=50, verbose_name='Link interno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Página ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Seção de 'Agenda'",
                'verbose_name_plural': "Seções de 'Agendas'",
            },
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_set', to='core.ScheduleSection', verbose_name='Seção relacionada'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speaker_event_set', to='core.Speaker', verbose_name='Lista de autores'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='event_set', to='core.EventTag', verbose_name='Lista de tags'),
        ),
    ]
